version: '3.8'

services:
  postgres:
    container_name: postgres_nest_react_community
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_react_community  
      PGDATA: /data_nest_react_community/postgres
    volumes:
       - postgres:/data_nest_react_community/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_nest_react_community
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/data_nest_react_community/pgadmin
    ports:
      - "8080:80"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis_nest_react_community
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_nest_react_communtiy_data:/data_nest_react_community/redis

  redis-commander:
    container_name: redis-commander_nest_react_community
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    redis_nest_react_communtiy_data: